
name: JSON UPDATE

on:
  schedule:
    - cron: "55 3 * * *"
    # 1日1回(おそらく)
  push:
    branches: [ main ]
    # プッシュ時に動作する

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      # [Setup] Node.js
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      
      # [Setup] npm i
      - name: npm install command
        run: yarn install

      # [RUN]  
      - name: Run
        run: yarn all

      # git add & git commit
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add changes" -a

      # git push
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # deploy
      - name: deploy webhook
        run: curl -X POST -d {} ${{ secrets.DEPLOY_WEBHOOK_URL }}